#!/bin/sh
# bump14
if [ ! -e .extracted/complete ]; then
    mkdir -p .extracted
    tar xfvz streamer.tgz -C .extracted
    touch .extracted/complete
fi
export LD_LIBRARY_PATH=$PWD/.extracted
/usr/bin/python2.7 input_forwarder.py &
exec python3 ./streamlink_wrap.py
